# Generated by Django 6.0 on 2026-01-03 14:29

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("patients", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Visit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "visit_datetime",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("chief_complaint", models.CharField(blank=True, max_length=255)),
                (
                    "clinical_notes",
                    models.TextField(help_text="Free text clinical notes"),
                ),
                ("diagnosis", models.CharField(blank=True, max_length=255)),
                ("treatment_plan", models.TextField(blank=True)),
                ("follow_up_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "doctor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="doctor_visits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="visits",
                        to="patients.patient",
                    ),
                ),
            ],
            options={
                "ordering": ["-visit_datetime"],
                "indexes": [
                    models.Index(
                        fields=["visit_datetime"], name="visits_visi_visit_d_348ffd_idx"
                    )
                ],
            },
        ),
    ]
