# Generated by Django 6.0 on 2026-02-09 13:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinics", "0001_initial"),
        ("patients", "0002_patient_clinic_and_more"),
        ("visits", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="visit",
            name="clinic",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="visits",
                to="clinics.clinic",
            ),
        ),
        migrations.AddIndex(
            model_name="visit",
            index=models.Index(
                fields=["clinic", "visit_datetime"],
                name="visits_visi_clinic__7cd38f_idx",
            ),
        ),
    ]
