# Generated by Django 6.0 on 2026-02-09 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinics", "0002_backfill_default_clinic"),
        ("visits", "0002_visit_clinic_visit_visits_visi_clinic__7cd38f_idx"),
    ]

    operations = [
        migrations.AlterField(
            model_name="visit",
            name="clinic",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="visits",
                to="clinics.clinic",
            ),
        ),
    ]
