# Generated by Django 6.0 on 2026-05-22 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0002_backfill_default_clinic'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='subscription_status',
            field=models.CharField(choices=[('trialing', 'Trialing'), ('active', 'Active'), ('expired', 'Expired')], default='trialing', max_length=20),
        ),
        migrations.AddField(
            model_name='clinic',
            name='trial_ends_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
