# Generated by Django 6.0 on 2026-06-27 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0005_backfill_paid_until'),
    ]

    operations = [
        migrations.CreateModel(
            name='RenewalReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('trial', 'Trial ending'), ('paid', 'Paid subscription ending')], max_length=10)),
                ('period_end', models.DateField(help_text='The trial_ends_at / paid_until this reminder was for')),
                ('days_before', models.PositiveSmallIntegerField(help_text='Days before period_end (0 = on the day)')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renewal_reminders', to='clinics.clinic')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('clinic', 'kind', 'period_end', 'days_before'), name='unique_reminder_per_period_offset')],
            },
        ),
    ]
