# Generated by Django 6.0 on 2026-02-09 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("clinics", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="clinic",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="users",
                to="clinics.clinic",
            ),
        ),
    ]
