"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv
from django.utils.translation import gettext_lazy as _

try:
    import dj_database_url as _dj_db
except ImportError:
    _dj_db = None

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load .env file if it exists (development only — production uses real env vars)
load_dotenv(BASE_DIR / ".env")


# ── Environment helpers ──────────────────────────────────────────────────────
# Read sensitive values from environment variables.
# In development, defaults are used so nothing breaks.
# In production, set these as real environment variables (never commit them).
# -----------------------------------------------------------------------------

SECRET_KEY = os.environ.get(
    "SECRET_KEY",
    "django-insecure-$qz6v-^o=&9hkf@verwp0+8m+pou48e*_)mga092zpz10piu-v",
)

DEBUG = os.environ.get("DEBUG", "True") == "True"

ALLOWED_HOSTS = os.environ.get("ALLOWED_HOSTS", "localhost,127.0.0.1").split(",")


# Application definition

INSTALLED_APPS = [
    "storages",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "accounts",
    "patients",
    "visits",
    "files",
    "audit",
    "clinics",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.locale.LocaleMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "clinics.middleware.ClinicMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        'DIRS': [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.template.context_processors.i18n",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

_DATABASE_URL = os.environ.get("DATABASE_URL")
if _DATABASE_URL and _dj_db:
    DATABASES = {"default": _dj_db.parse(_DATABASE_URL, conn_max_age=600)}
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en"

LANGUAGES = [
    ("en", _("English")),
    ("ar", _("Arabic")),
]

LOCALE_PATHS = [BASE_DIR / "locale"]

TIME_ZONE = "Africa/Cairo"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [BASE_DIR / "static"]


AUTH_USER_MODEL = 'accounts.User'


LOGIN_URL = "/login/"
LOGIN_REDIRECT_URL = "/dashboard/"
LOGOUT_REDIRECT_URL = "/login/"


# ── Email ────────────────────────────────────────────────────────────────────
# Development default: prints emails to the terminal (no SMTP needed).
# Production: set EMAIL_BACKEND, EMAIL_HOST, EMAIL_HOST_USER, EMAIL_HOST_PASSWORD
# as environment variables on your server.
# -----------------------------------------------------------------------------
EMAIL_BACKEND = os.environ.get(
    "EMAIL_BACKEND",
    "django.core.mail.backends.console.EmailBackend",
)
DEFAULT_FROM_EMAIL = os.environ.get("DEFAULT_FROM_EMAIL", "noreply@clinicrecords.local")

EMAIL_HOST          = os.environ.get("EMAIL_HOST", "")
EMAIL_PORT          = int(os.environ.get("EMAIL_PORT", "587"))
EMAIL_USE_TLS       = os.environ.get("EMAIL_USE_TLS", "True") == "True"
EMAIL_USE_SSL       = os.environ.get("EMAIL_USE_SSL", "False") == "True"
EMAIL_HOST_USER     = os.environ.get("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_HOST_PASSWORD", "")


# ── Billing (manual InstaPay) ─────────────────────────────────────────────────
# INSTAPAY_ADDRESS: your IPA shown to clinics on the paywall.
# PAYMENT_NOTIFICATION_EMAIL: where new-payment alerts are sent for you to review.
# -----------------------------------------------------------------------------
INSTAPAY_ADDRESS = os.environ.get("INSTAPAY_ADDRESS", "documed@instapay")
MONTHLY_PRICE_EGP = int(os.environ.get("MONTHLY_PRICE_EGP", "1500"))
PAYMENT_NOTIFICATION_EMAIL = os.environ.get(
    "PAYMENT_NOTIFICATION_EMAIL", "mustafaelmahdy52@gmail.com"
)

# Public base URL, used to build absolute links in emails (no request available
# in management commands / cron).
SITE_URL = os.environ.get("SITE_URL", "https://documed.health")


# ── File Storage ─────────────────────────────────────────────────────────────
# If R2 credentials are present → store media files in Cloudflare R2.
# Otherwise fall back to local filesystem (development default).
# -----------------------------------------------------------------------------

_R2_KEY = os.environ.get("R2_ACCESS_KEY_ID", "")

STORAGES = {
    "default": {
        "BACKEND": (
            "storages.backends.s3boto3.S3Boto3Storage"
            if _R2_KEY
            else "django.core.files.storage.FileSystemStorage"
        ),
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

if _R2_KEY:
    AWS_ACCESS_KEY_ID       = _R2_KEY
    AWS_SECRET_ACCESS_KEY   = os.environ.get("R2_SECRET_ACCESS_KEY", "")
    AWS_STORAGE_BUCKET_NAME = os.environ.get("R2_BUCKET_NAME", "documed-media")
    AWS_S3_ENDPOINT_URL     = os.environ.get("R2_ENDPOINT_URL", "")
    AWS_S3_REGION_NAME      = "auto"
    AWS_DEFAULT_ACL         = "private"
    AWS_QUERYSTRING_AUTH    = True   # pre-signed URLs — files are not publicly accessible
    AWS_S3_FILE_OVERWRITE   = False  # never silently replace an existing file


# ── Security ──────────────────────────────────────────────────────────────────
# CSRF_TRUSTED_ORIGINS must include the Render domain and any custom domain.
# Set in environment: CSRF_TRUSTED_ORIGINS=https://documed.onrender.com,https://dcumed.health
# ------------------------------------------------------------------------------

_csrf_raw = os.environ.get("CSRF_TRUSTED_ORIGINS", "")
CSRF_TRUSTED_ORIGINS = [o.strip() for o in _csrf_raw.split(",") if o.strip()]


# ── Sentry ────────────────────────────────────────────────────────────────────
_sentry_dsn = os.environ.get("SENTRY_DSN", "")
if _sentry_dsn:
    import sentry_sdk
    sentry_sdk.init(
        dsn=_sentry_dsn,
        environment="production" if not DEBUG else "development",
        traces_sample_rate=0.2,
        send_default_pii=False,
    )

