# Generated by Django 6.0 on 2026-02-09 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0002_auditevent_display"),
        ("clinics", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="auditevent",
            name="clinic",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="audit_events",
                to="clinics.clinic",
            ),
        ),
    ]
