# Generated by Django 6.0 on 2026-02-09 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0003_auditevent_clinic"),
        ("clinics", "0002_backfill_default_clinic"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditevent",
            name="clinic",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="audit_events",
                to="clinics.clinic",
            ),
        ),
    ]
