# Generated by Django 6.0 on 2026-02-11 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0004_alter_auditevent_clinic"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditevent",
            name="action",
            field=models.CharField(
                choices=[
                    ("patient_created", "Patient created"),
                    ("visit_created", "Visit created"),
                    ("visit_edited", "Visit edited"),
                    ("patient_viewed", "Patient viewed"),
                    ("file_uploaded", "File uploaded"),
                    ("file_downloaded", "File downloaded"),
                    ("file_deleted", "File deleted"),
                ],
                max_length=50,
            ),
        ),
    ]
