# Generated by Django 6.0 on 2026-02-11 23:16

import django.db.models.deletion
import django.utils.timezone
import files.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clinics", "0002_backfill_default_clinic"),
        ("patients", "0004_patient_unique_national_id_per_clinic_and_more"),
        ("visits", "0003_alter_visit_clinic"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Attachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(upload_to=files.models.attachment_upload_path),
                ),
                ("original_filename", models.CharField(max_length=255)),
                (
                    "file_type",
                    models.CharField(
                        choices=[
                            ("xray", "X-Ray"),
                            ("lab", "Lab Result"),
                            ("prescription", "Prescription"),
                            ("report", "Medical Report"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                (
                    "file_size",
                    models.PositiveIntegerField(help_text="File size in bytes"),
                ),
                ("mime_type", models.CharField(blank=True, max_length=100)),
                (
                    "title",
                    models.CharField(
                        blank=True, help_text="Optional description", max_length=255
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "uploaded_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "clinic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attachments",
                        to="clinics.clinic",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="patients.patient",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_files",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "visit",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional: Link to a specific visit",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="attachments",
                        to="visits.visit",
                    ),
                ),
            ],
            options={
                "ordering": ["-uploaded_at"],
                "indexes": [
                    models.Index(
                        fields=["clinic", "patient"],
                        name="files_attac_clinic__5d4161_idx",
                    ),
                    models.Index(
                        fields=["clinic", "uploaded_at"],
                        name="files_attac_clinic__266925_idx",
                    ),
                    models.Index(
                        fields=["patient", "-uploaded_at"],
                        name="files_attac_patient_1beb1e_idx",
                    ),
                ],
            },
        ),
    ]
