# Generated by Django 6.0 on 2026-01-03 14:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=255)),
                (
                    "normalized_name",
                    models.CharField(db_index=True, editable=False, max_length=255),
                ),
                ("phone", models.CharField(blank=True, db_index=True, max_length=30)),
                (
                    "national_id",
                    models.CharField(blank=True, db_index=True, max_length=30),
                ),
                (
                    "sex",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female"), ("U", "Unknown")],
                        default="U",
                        max_length=10,
                    ),
                ),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("address", models.CharField(blank=True, max_length=255)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["full_name"],
                "indexes": [
                    models.Index(
                        fields=["normalized_name"],
                        name="patients_pa_normali_d6dbc0_idx",
                    ),
                    models.Index(fields=["phone"], name="patients_pa_phone_fc49bb_idx"),
                    models.Index(
                        fields=["national_id"], name="patients_pa_nationa_70cc77_idx"
                    ),
                ],
            },
        ),
    ]
