# Generated by Django 6.0 on 2026-02-09 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinics", "0002_backfill_default_clinic"),
        ("patients", "0002_patient_clinic_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="clinic",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="patients",
                to="clinics.clinic",
            ),
        ),
    ]
