# Generated by Django 6.0 on 2026-02-11 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinics", "0002_backfill_default_clinic"),
        ("patients", "0003_alter_patient_clinic"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="patient",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("national_id__isnull", False),
                    models.Q(("national_id", ""), _negated=True),
                ),
                fields=("clinic", "national_id"),
                name="unique_national_id_per_clinic",
            ),
        ),
        migrations.AddConstraint(
            model_name="patient",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("phone__isnull", False), models.Q(("phone", ""), _negated=True)
                ),
                fields=("clinic", "phone"),
                name="unique_phone_per_clinic",
            ),
        ),
    ]
