# Generated by Django 6.0 on 2026-02-16 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_patient_unique_national_id_per_clinic_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='patient',
            name='unique_phone_per_clinic',
        ),
    ]
